version: '3'
services:
  pyflask:
    build:
      dockerfile: ./Dockerfile.docker
      context: .
      # labels:
      #   containerType: "kontain"
    image: sandman2k/pyflaskdocker
    ports:
      - "5000:5000"
    container_name: pyflaskex
    logging:
      driver: awslogs
      options: 
        awslogs-group: ecstestclstr2 
        awslogs-region: us-west-2
        awslogs-stream-prefix: pyflask
