---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: quote
spec:
    replicas: 1
    selector:
        matchLabels:
            app: quote
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: quote
        spec:
            containers:
            -   name: backend
                image: docker.io/datawire/quote:0.4.1
                ports:
                -   containerPort: 8080
---
# ref: https://www.suse.com/c/rancher_blog/deploy-an-ingress-controller-on-k3s/
apiVersion: v1
kind: Service
metadata:
    name: quote
spec:
    ports:
    -   name: http
        port: 80
        targetPort: 8080
    selector:
        app: quote
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: quote
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /give-me-a-quote/
            pathType: Prefix
            backend:
              service:
                name: quote
                port:
                  number: 80
