---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: springbootapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      runtimeClassName: kontain
      containers:
      - name: springbootapp
        image: sandman2k/springboothello:1.0
        ports:
        - containerPort: 8080