---
apiVersion: v1
kind: Service
metadata:
  name: springboothello
  labels:
    app: springboothello
spec:
  type: ClusterIP 
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: springboothello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboothello
  labels:
    app: springboothello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboothello
  template:
    metadata:
      labels:
        app: springboothello
    spec:
      runtimeClassName: kontain
      volumes:
        - name: springboot-vol
          persistentVolumeClaim:
            claimName: springboot-pv-claim
      containers:
      - name: springboothello
        image: sandman2k/testspringboothello:1.0
        imagePullPolicy: Always
        # command: ["sleep", "infinity"]
        ports:
         - containerPort: 8080
        volumeMounts:
          - mountPath: "/usr/share/kontain"
            name: springboot-vol
