# This is a basic workflow to help you get started with Actions

name: Package Downloadable Assets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          REPO_FOLDER=`pwd`
          cd downloads
          tar -C $REPO_FOLDER/_examples/simple/ -cvf hellokontain.tar.gz .
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads

      - name: Set up S3cmd cli tool
        # You may pin to the exact commit or the version.
        # uses: s3-actions/s3cmd@4a2a23baac468fd99c43dddc2be4a2d614921022
        uses: s3-actions/s3cmd@v1.1
        with:
          # config provider to make it easier to use the cli as action
          provider: aws
          # s3 region
          region: us-west-2
          # s3 access key
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # s3 secret key
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Interact with object storage
        run: |
          cd downloads
          s3cmd cp hellokontain.tar.gz s3://guide-assets/downloads/
          s3cmd info s3://guide-assets/downloads/

